### ISSUE TITLE
A question about masking strategy

### ISSUE THREAD

**Issue by xiaohu2015** [microsoft/SimMIM#2]
For Swin Transformer, the default masked patch size is 32x32, but the first patch embedding layer needs 4x4 patch size. So I want know if the learned masked token is designed for 4x4 patch size, but you also use 32x32 masking strategy?

**Comment by tf24-karatzhong** [comment]
Same confusion, please give some hints, really appreciate it

**Comment by ancientmooner** [comment]
> For Swin Transformer, the default masked patch size is 32x32, but the first patch embedding layer needs 4x4 patch size. So I want know if the learned masked token is designed for 4x4 patch size, but you also use 32x32 masking strategy?

The patch size and masking size can be independent, due to that raw pixel values are predicted.
