### ISSUE TITLE
Information about relative positional encoding

### ISSUE THREAD

**Issue by marc345** [microsoft/SimMIM#4]
Hi thanks for sharing your work.
I was wondering if someone can provide we with some additional information about the following line (and the two lines after that):

https://github.com/microsoft/SimMIM/blob/519ae7b0999b9d720daa61e3848cd41b8fbd9978/models/vision_transformer.py#L78

Why exactly do we subtract 3, 2 and 1 respectively? And isn't the statement on line 80 overwriting the statement two lines prior on line 78?

What exactly does the relative_position_index matrix hold?

**Comment by ancientmooner** [comment]
> Hi thanks for sharing your work. I was wondering if someone can provide we with some additional information about the following line (and the two lines after that):
> 
> https://github.com/microsoft/SimMIM/blob/519ae7b0999b9d720daa61e3848cd41b8fbd9978/models/vision_transformer.py#L78
> 
> Why exactly do we subtract 3, 2 and 1 respectively? And isn't the statement on line 80 overwriting the statement two lines prior on line 78?
> 
> What exactly does the relative_position_index matrix hold?

This is for tackling [CLS] token. This was used for ViT. For Swin Transformer, [CLS] token is not used by default.
