### ISSUE TITLE
About data augment

### ISSUE THREAD

**Issue by peiyingxin** [microsoft/SimMIM#5]
thanks for sharing your excellent work！
i have a question about data augment in pretraining：
have you try other data augment like   RandomResizedCrop() + RandomHorizontalFlip() + RandomVerticalFlip()   or  other  compose？
and RandomResizedCrop() + RandomHorizontalFlip() work the best?

**Comment by ancientmooner** [comment]
> thanks for sharing your excellent work！ i have a question about data augment in pretraining： have you try other data augment like RandomResizedCrop() + RandomHorizontalFlip() + RandomVerticalFlip() or other compose？ and RandomResizedCrop() + RandomHorizontalFlip() work the best?

We did not try it. RandomVerticalFlip() was rarely used in vision applications such as image classification and object detection. Human beings also do not handle well with upside down images.
