### ISSUE TITLE
USE_RPB and USE_SHARED_RPB are inconsistent in pretrain and finetune

### ISSUE THREAD

**Issue by haooooooqi** [microsoft/SimMIM#8]
Hi, Thanks for the amazing work and share the oss code!
I was wondering if you could share the reason of this?

`MODEL.VIT.USE_RPB: True` in simmim_finetune__vit_base__img224__800ep.yaml
`MODEL.VIT.USE_SHARED_RPB: True` in simmim_pretrain__vit_base__img224__800ep.yaml

Do we expect use the same RPB between pretrain and finetune?

Thanks,

**Comment by ancientmooner** [comment]
> 

This is inherited from BEiT. We use non-shared RPB by default. Sorry for the late reply.
